# -*- coding: utf-8 -*-
"""hf_summarizer_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/TC49501/e2f581496112f37b309805c88b1fe75e/hf_summarizer_app.ipynb
"""

!pip install transformers streamlit

from transformers import pipeline

# Load the summarizer pipeline with a pretrained model
summarizer = pipeline("summarization", model="google/pegasus-xsum")

def summarize_text(text):
    result = summarizer(text, max_length=130, min_length=30, do_sample=False)
    return result[0]['summary_text']

from IPython.display import display
import ipywidgets as widgets

text_area = widgets.Textarea(
    value='Paste a long text here...',
    placeholder='Enter text to summarize',
    description='Input:',
    layout=widgets.Layout(width='100%', height='200px')
)

button = widgets.Button(description="Summarize")
output = widgets.Output()

def on_button_click(b):
    with output:
        output.clear_output()
        summary = summarize_text(text_area.value)
        print("📝 Summary:\n", summary)

button.on_click(on_button_click)

display(text_area, button, output)
